# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-18 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardatamodel',
            name='mobileno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
